2023-08-12 04:06:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42001-214]
2023-08-12 04:22:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42001-214]
2023-08-12 04:22:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42001-214]
2023-08-12 04:24:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42001-214]
2023-08-12 04:28:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42001-214]
2023-08-12 14:30:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42001-214]
2023-08-12 14:54:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42001-214]
2023-08-12 14:59:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42001-214]
2023-08-12 15:00:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "select u1_0.id,u1_0.email,u1_0.firstName,u1_0.isActive,u1_0.lastName,u1_0.password,u1_0.phoneNumber from [*]User u1_0"; expected "identifier"; SQL statement:
select u1_0.id,u1_0.email,u1_0.firstName,u1_0.isActive,u1_0.lastName,u1_0.password,u1_0.phoneNumber from User u1_0 [42001-214]
2023-08-12 15:01:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42001-214]
2023-08-12 15:01:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "select u1_0.id,u1_0.email,u1_0.firstName,u1_0.isActive,u1_0.lastName,u1_0.password,u1_0.phoneNumber from [*]User u1_0 where u1_0.id=?"; expected "identifier"; SQL statement:
select u1_0.id,u1_0.email,u1_0.firstName,u1_0.isActive,u1_0.lastName,u1_0.password,u1_0.phoneNumber from User u1_0 where u1_0.id=? [42001-214]
2023-08-12 15:07:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table [*]User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id))"; expected "identifier"; SQL statement:
create table User (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42001-214]
2023-08-12 15:19:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "APPUSER" already exists; SQL statement:
create table AppUser (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42101-214]
2023-08-12 15:22:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "APPUSER" already exists; SQL statement:
create table AppUser (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42101-214]
2023-08-12 15:28:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "APPUSER" already exists; SQL statement:
create table AppUser (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42101-214]
2023-08-12 15:29:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "APPUSER" already exists; SQL statement:
create table AppUser (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42101-214]
2023-08-12 15:37:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "APPUSER" already exists; SQL statement:
create table AppUser (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42101-214]
2023-08-12 15:53:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "APPUSER" already exists; SQL statement:
create table AppUser (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42101-214]
2023-08-12 16:01:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "APPUSER" already exists; SQL statement:
create table AppUser (isActive boolean, phoneNumber integer not null, id bigint generated by default as identity, email varchar(255), firstName varchar(255), lastName varchar(255), password varchar(255), primary key (id)) [42101-214]
2023-08-13 13:44:18 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: Could not open file C:/Users/my pc/Desktop/savingsapp/file/db.mv.db [2.1.214/1]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: Could not open file C:/Users/my pc/Desktop/savingsapp/file/db.mv.db [2.1.214/1]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 23 more
Caused by: org.h2.mvstore.MVStoreException: Could not open file C:/Users/my pc/Desktop/savingsapp/file/db.mv.db [2.1.214/1]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:185)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 17 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:388)
	at org.h2.mvstore.FileStore.open(FileStore.java:182)
	... 19 more
2023-08-13 13:44:22 database: opening C:/Users/my pc/Desktop/savingsapp/file/db
org.h2.message.DbException: IO Exception: "C:/Users/my pc/Desktop/savingsapp/file/db.mv.db" [90028-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:171)
	at org.h2.mvstore.db.Store.<init>(Store.java:145)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: "C:/Users/my pc/Desktop/savingsapp/file/db.mv.db" [90028-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 18 more
Caused by: org.h2.mvstore.MVStoreException: Could not open file C:/Users/my pc/Desktop/savingsapp/file/db.mv.db [2.1.214/1]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:185)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	... 15 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:388)
	at org.h2.mvstore.FileStore.open(FileStore.java:182)
	... 19 more
2023-08-13 13:45:55 database: CREATE CACHED TABLE "PUBLIC"."APPUSER"(
    "ISACTIVE" BOOLEAN,
    "PHONENUMBER" CHARACTER VARYING(255) NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_72232AA8_39DC_4AE3_BA23_B933B809B89D" NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "FIRSTNAME" CHARACTER VARYING(255),
    "LASTNAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255)
)
org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: "C:/Users/my pc/Desktop/savingsapp/file/db.mv.db"; SQL statement:
CREATE CACHED TABLE "PUBLIC"."APPUSER"(
    "ISACTIVE" BOOLEAN,
    "PHONENUMBER" CHARACTER VARYING(255) NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_72232AA8_39DC_4AE3_BA23_B933B809B89D" NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "FIRSTNAME" CHARACTER VARYING(255),
    "LASTNAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255)
) [90028-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:171)
	at org.h2.mvstore.db.Store.createTable(Store.java:223)
	at org.h2.schema.Schema.createTable(Schema.java:776)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:112)
	at org.h2.engine.MetaRecord.prepareAndExecute(MetaRecord.java:77)
	at org.h2.engine.Database.executeMeta(Database.java:660)
	at org.h2.engine.Database.executeMeta(Database.java:634)
	at org.h2.engine.Database.<init>(Database.java:357)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.mvstore.MVStoreException: Reading from file sun.nio.ch.FileChannelImpl@30dc8c56 failed at 12467 (length -1), read 0, remaining 192 [2.1.214/1]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:470)
	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
	at org.h2.mvstore.Chunk.readBufferForPage(Chunk.java:422)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2569)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:633)
	at org.h2.mvstore.MVMap.readOrCreateRootPage(MVMap.java:658)
	at org.h2.mvstore.MVMap.setRootPos(MVMap.java:643)
	at org.h2.mvstore.MVStore.openMap(MVStore.java:702)
	at org.h2.mvstore.MVStore.openMap(MVStore.java:648)
	at org.h2.mvstore.tx.TransactionStore.openMap(TransactionStore.java:564)
	at org.h2.mvstore.tx.TransactionStore.openVersionedMap(TransactionStore.java:550)
	at org.h2.mvstore.tx.Transaction.openMap(Transaction.java:456)
	at org.h2.mvstore.db.MVPrimaryIndex.<init>(MVPrimaryIndex.java:53)
	at org.h2.mvstore.db.MVTable.<init>(MVTable.java:156)
	at org.h2.mvstore.db.Store.createTable(Store.java:219)
	... 20 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:816)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:793)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:456)
	... 34 more
2023-08-13 13:45:55 database: opening C:/Users/my pc/Desktop/savingsapp/file/db
org.h2.message.DbException: IO Exception: "C:/Users/my pc/Desktop/savingsapp/file/db.mv.db" [90028-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:171)
	at org.h2.mvstore.db.Store.createTable(Store.java:223)
	at org.h2.schema.Schema.createTable(Schema.java:776)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:112)
	at org.h2.engine.MetaRecord.prepareAndExecute(MetaRecord.java:77)
	at org.h2.engine.Database.executeMeta(Database.java:660)
	at org.h2.engine.Database.executeMeta(Database.java:634)
	at org.h2.engine.Database.<init>(Database.java:357)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: "C:/Users/my pc/Desktop/savingsapp/file/db.mv.db"; SQL statement:
CREATE CACHED TABLE "PUBLIC"."APPUSER"(
    "ISACTIVE" BOOLEAN,
    "PHONENUMBER" CHARACTER VARYING(255) NOT NULL,
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_72232AA8_39DC_4AE3_BA23_B933B809B89D" NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "FIRSTNAME" CHARACTER VARYING(255),
    "LASTNAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255)
) [90028-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 23 more
Caused by: org.h2.mvstore.MVStoreException: Reading from file sun.nio.ch.FileChannelImpl@30dc8c56 failed at 12467 (length -1), read 0, remaining 192 [2.1.214/1]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:470)
	at org.h2.mvstore.FileStore.readFully(FileStore.java:98)
	at org.h2.mvstore.Chunk.readBufferForPage(Chunk.java:422)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2569)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:633)
	at org.h2.mvstore.MVMap.readOrCreateRootPage(MVMap.java:658)
	at org.h2.mvstore.MVMap.setRootPos(MVMap.java:643)
	at org.h2.mvstore.MVStore.openMap(MVStore.java:702)
	at org.h2.mvstore.MVStore.openMap(MVStore.java:648)
	at org.h2.mvstore.tx.TransactionStore.openMap(TransactionStore.java:564)
	at org.h2.mvstore.tx.TransactionStore.openVersionedMap(TransactionStore.java:550)
	at org.h2.mvstore.tx.Transaction.openMap(Transaction.java:456)
	at org.h2.mvstore.db.MVPrimaryIndex.<init>(MVPrimaryIndex.java:53)
	at org.h2.mvstore.db.MVTable.<init>(MVTable.java:156)
	at org.h2.mvstore.db.Store.createTable(Store.java:219)
	... 20 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:816)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:793)
	at org.h2.mvstore.DataUtils.readFully(DataUtils.java:456)
	... 34 more
2023-08-13 13:54:46 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: Could not open file C:/Users/my pc/Desktop/savingsapp/file/db.mv.db [2.1.214/1]" [50000-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.message.DbException.convert(DbException.java:395)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:125)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3318)
	at org.h2.mvstore.MVStore.panic(MVStore.java:593)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:469)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: Could not open file C:/Users/my pc/Desktop/savingsapp/file/db.mv.db [2.1.214/1]" [50000-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 23 more
Caused by: org.h2.mvstore.MVStoreException: Could not open file C:/Users/my pc/Desktop/savingsapp/file/db.mv.db [2.1.214/1]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:185)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	... 17 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:388)
	at org.h2.mvstore.FileStore.open(FileStore.java:182)
	... 19 more
2023-08-13 13:54:46 database: opening C:/Users/my pc/Desktop/savingsapp/file/db
org.h2.message.DbException: IO Exception: "C:/Users/my pc/Desktop/savingsapp/file/db.mv.db" [90028-214]
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:171)
	at org.h2.mvstore.db.Store.<init>(Store.java:145)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: "C:/Users/my pc/Desktop/savingsapp/file/db.mv.db" [90028-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:554)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	... 18 more
Caused by: org.h2.mvstore.MVStoreException: Could not open file C:/Users/my pc/Desktop/savingsapp/file/db.mv.db [2.1.214/1]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:185)
	at org.h2.mvstore.FileStore.open(FileStore.java:128)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:452)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	... 15 more
Caused by: java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:388)
	at org.h2.mvstore.FileStore.open(FileStore.java:182)
	... 19 more
